//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsonFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meteorite
    {
        public int MeteoriteID { get; set; }
        public string Name { get; set; }
        public string Classification { get; set; }
        public string Mass { get; set; }
        public int FallID { get; set; }
        public int YearID { get; set; }
    
        public virtual Fall Fall { get; set; }
        public virtual Year Year { get; set; }
    }
}
