//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsonFinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NightSkyObservatoryEntitiesConnection : DbContext
    {
        public NightSkyObservatoryEntitiesConnection()
            : base("name=NightSkyObservatoryEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fall> Falls { get; set; }
        public virtual DbSet<Meteorite> Meteorites { get; set; }
        public virtual DbSet<UFO> UFOes { get; set; }
        public virtual DbSet<Year> Years { get; set; }
    }
}
